### ISSUE TITLE
將';改為拼音切換

### ISSUE THREAD

**Issue by delphinuz** [ianzhuo/rime-liur-lua#4]
```
phonetic:
  tag: phonetic
  prefix: "';"
  suffix: "'"

pinyin:
  tag: pinyin
  dictionary: luna_pinyin
  prefix: "`"
# 漢語拼音輸入以「`」引導
  suffix: "'"
```

您好，因為常用拼音，想將上面 '; 改為拼音，而不用注音，但改過來後無法出現拼音，請幫忙看是否有誤，謝謝。

```

pinyin:
  tag: pinyin
  dictionary: luna_pinyin
  prefix: "';"
# 漢語拼音輸入以「`」引導
  suffix: "'"
```
